; Inno Setup script for Helbreath
; Generated by make_installer.py

[Setup]
AppName=Helbreath
AppVersion=0.2.11
AppPublisher=Helbreath
DefaultDirName={autopf}\Helbreath
DefaultGroupName=Helbreath
OutputDir=C:\Users\ShadowEvil\source\Repos3\Helbreath-3.82\tools\InstallerCreator
OutputBaseFilename=Helbreath_v0.2.11_setup
Compression=lzma2
SolidCompression=yes
SetupIconFile=compiler:SetupClassicIcon.ico
UninstallDisplayIcon={app}\Game_x64_win.exe
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
DisableWelcomePage=no
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
Name: "{app}"; Permissions: users-modify

[Files]
Source: "C:\Users\ShadowEvil\source\Repos3\Helbreath-3.82\tools\InstallerCreator\Helbreath\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Helbreath"; Filename: "{app}\Game_x64_win.exe"
Name: "{autodesktop}\Helbreath"; Filename: "{app}\Game_x64_win.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"

[Run]
Filename: "{app}\Game_x64_win.exe"; Description: "Launch Helbreath"; Flags: nowait postinstall skipifsilent
