// Auto-generated by version_gen.py — do not edit manually
#pragma once

// Client version
#define VER_CLIENT_MAJOR         0
#define VER_CLIENT_MINOR         2
#define VER_CLIENT_PATCH         52
#define VER_CLIENT_BUILD         357
#define VER_CLIENT_FILEVERSION   0,2,52,357
#define VER_CLIENT_DISPLAY       "0.2.52-alpha"
#define VER_CLIENT_FULL          "0.2.52-alpha+build.357"

// Server version
#define VER_SERVER_MAJOR         0
#define VER_SERVER_MINOR         1
#define VER_SERVER_PATCH         24
#define VER_SERVER_BUILD         247
#define VER_SERVER_FILEVERSION   0,1,24,247
#define VER_SERVER_DISPLAY       "0.1.24-alpha"
#define VER_SERVER_FULL          "0.1.24-alpha+build.247"
