// Auto-generated by version_gen.py — do not edit manually
#pragma once

namespace hb::version
{

namespace compatibility
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 14;
constexpr int build_number = 0;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.14-alpha";
constexpr const char* full_version = "0.2.14-alpha+build.0";
} // namespace compatibility

namespace server
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 0;
constexpr int build_number = 247;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2-alpha";
constexpr const char* full_version = "0.2.0-alpha+build.247";
} // namespace server

namespace client
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 52;
constexpr int build_number = 357;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.52-alpha";
constexpr const char* full_version = "0.2.52-alpha+build.357";
} // namespace client

constexpr const char* build_timestamp = "2026-09-17T13:53:29";

} // namespace hb::version
