#!/usr/bin/env python3
"""
Fix remaining m_attribute references and send_event_to_near_client_type_b ambiguity.
"""
import re
import sys
import os

DRY_RUN = "--dry-run" in sys.argv

# Pattern 1: send_event_to_near_client_type_b calls ending with m_enchant_bonus)
# Need to wrap m_enchant_bonus in static_cast<uint32_t>(...)
# BUT skip AccountSqliteStore.cpp lines

# Pattern 2: send_event calls ending with m_attribute) — replace m_attribute with m_enchant_bonus and cast

# Pattern 3: pkt.attribute = item->m_attribute → item->copy_attributes_to(pkt)

# Pattern 4: entry->attribute = item->m_attribute → item->copy_attributes_to(*entry)

# Pattern 5: copy->m_attribute = original->m_attribute → copy->copy_attributes_from(original)

# Pattern 6: item->m_attribute = attribute (direct assignment) → decompose

# Files to process
SERVER_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "Sources", "Server")
CLIENT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "Sources", "Client")

changes = []

def process_file(filepath, short_name):
	with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
		content = f.read()
	original = content

	# Pattern 1: Fix send_event ambiguity — item->m_enchant_bonus) at end of send_event call
	# Match: item_color, item->m_enchant_bonus); or item_color, item_var->m_enchant_bonus);
	# Replace the last arg with static_cast<uint32_t>(...)
	# We match the pattern: ", <var>->m_enchant_bonus);"
	def fix_enchant_cast(m):
		accessor = m.group(1)
		suffix = m.group(2)
		return f", static_cast<uint32_t>({accessor}->m_enchant_bonus)){suffix}"

	# Only in files that call send_event_to_near_client_type_b
	if "send_event_to_near_client_type_b" in content:
		# Find lines with enchant_bonus) that are part of send_event calls
		# Match: , <anything>->m_enchant_bonus); at end of line
		pattern = r', (\S+)->m_enchant_bonus\)(;.*)'
		content = re.sub(pattern, fix_enchant_cast, content)

	# Pattern 2: Fix remaining m_attribute) in send_event calls
	# These are long accessor chains: ...->m_item_list[item_index]->m_attribute);
	if "send_event_to_near_client_type_b" in content:
		def fix_attr_to_enchant(m):
			accessor = m.group(1)
			suffix = m.group(2)
			return f", static_cast<uint32_t>({accessor}->m_enchant_bonus)){suffix}"
		pattern = r', (\S+)->m_attribute\)(;.*)'
		content = re.sub(pattern, fix_attr_to_enchant, content)

	# Pattern 3: pkt.attribute = ...->m_attribute; → copy_attributes_to
	# Match: pkt_var.attribute = item_expr->m_attribute;
	def fix_pkt_attribute(m):
		pkt_var = m.group(1)
		item_expr = m.group(2)
		return f"{item_expr}->copy_attributes_to({pkt_var});"
	content = re.sub(
		r'(\w+)\.attribute\s*=\s*(\S+)->m_attribute;',
		fix_pkt_attribute, content
	)

	# Pattern 3b: pkt_var.custom_made through pkt_var.enchant_bonus (6-line block from script)
	# These were already correctly generated by the first script — skip

	# Pattern 4: entry->attribute = ...->m_attribute; → copy_attributes_to
	def fix_entry_attribute(m):
		entry_var = m.group(1)
		item_expr = m.group(2)
		return f"{item_expr}->copy_attributes_to(*{entry_var});"
	content = re.sub(
		r'(\w+)->attribute\s*=\s*(\S+)->m_attribute;',
		fix_entry_attribute, content
	)

	# Pattern 5: copy->m_attribute = original->m_attribute → copy->copy_attributes_from(original)
	def fix_copy_attribute(m):
		copy_var = m.group(1)
		original_var = m.group(2)
		return f"{copy_var}->copy_attributes_from({original_var});"
	content = re.sub(
		r'(\w+)->m_attribute\s*=\s*(\w+)->m_attribute;',
		fix_copy_attribute, content
	)

	# Pattern 6: item->m_attribute = <integer>; (direct numeric assignment like = 0 or = 1)
	# Only match simple numeric values, not complex expressions
	def fix_direct_assign(m):
		item_var = m.group(1)
		value = int(m.group(2))
		if value == 0:
			return f"// attributes cleared (was m_attribute = 0)"
		elif value == 1:
			return f"{item_var}->m_custom_made = true;"
		else:
			return m.group(0)  # don't change complex values
	content = re.sub(
		r'(\w+)->m_attribute\s*=\s*(\d+);',
		fix_direct_assign, content
	)

	if content != original:
		if DRY_RUN:
			print(f"  [DRY RUN] Would modify {short_name}")
		else:
			with open(filepath, 'w', encoding='utf-8') as f:
				f.write(content)
			print(f"  Modified {short_name}")
		changes.append(short_name)
	else:
		print(f"  No changes: {short_name}")

# Process server files
server_files = [
	"ItemManager.cpp", "Game.cpp", "CraftingManager.cpp",
	"EntityManager.cpp", "FishingManager.cpp", "MagicManager.cpp",
	"MiningManager.cpp", "StatusEffectManager.cpp", "Map.cpp",
	"LoginServer.cpp",
]

print(f"=== fix_remaining_attributes.py {'[DRY RUN]' if DRY_RUN else '[APPLY]'} ===\n")

for f in server_files:
	path = os.path.join(SERVER_DIR, f)
	if os.path.exists(path):
		process_file(path, f"Server/{f}")

# Process client files
client_files = [
	"Game.cpp", "ItemNameFormatter.cpp", "InventoryManager.cpp",
	"NetworkMessages_Items.cpp", "NetworkMessages_Bank.cpp",
	"DialogBox_ItemUpgrade.cpp", "DialogBox_Magic.cpp",
]

for f in client_files:
	path = os.path.join(CLIENT_DIR, f)
	if os.path.exists(path):
		process_file(path, f"Client/{f}")

print(f"\nTotal: {len(changes)} files changed")
